### PR TITLE
Use hf_hub_download in the gradio demo to take advantage of cache

### PR DESCRIPTION
**Pull request by paulmaksimovich**

### CODE REVIEW

**Comment by paulmaksimovich** [comment]
@microsoft-github-policy-service agree

**Comment by ddenhamer** [comment]
@paulmaksimovich did you get the repo to run using this PR?

**Comment by paulmaksimovich** [comment]
@ddenhamer Yes, works right off the bat following the direction with a fresh clone and fresh conda env.

Screenshot from 2024-10-25 17-00-57

**Comment by Sheiphan** [comment]
This might not be the problem with the exact code that you are using, 
`hf_hub_download` is not downloading the .bin and .safetensors file for `icon_cation_blip2`.

I had to manually download and store it. It worked but any idea why is that happening?

I think you should use snapshot_download instead.

**Comment by abrichr** [comment]
See also [download.py](https://github.com/microsoft/OmniParser/pull/52/files#diff-0754e2389b0a4982ce0106c260cf218699e6f2061105043cc24acc7398d1d38b) from https://github.com/microsoft/OmniParser/pull/52

**Pull request closed without merging**
